import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {PlayerController} from './player.js';import {Weapon} from './weapon.js';import {Zombie} from './zombie.js';import {createWorld} from './world.js';
const root=document.querySelector('#game'),scene=new THREE.Scene();scene.background=new THREE.Color(0x090b0c);scene.fog=new THREE.Fog(0x090b0c,18,90);const camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.05,150);const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);root.appendChild(renderer.domElement);renderer.outputColorSpace=THREE.SRGBColorSpace;
scene.add(new THREE.HemisphereLight(0xaeb9ad,0x20251f,1.4));const sun=new THREE.DirectionalLight(0xc3cec0,1.5);sun.position.set(-20,30,10);scene.add(sun);createWorld(THREE,scene);
const joystick=document.querySelector('#joystick'),stick=document.querySelector('#stick'),look=document.querySelector('#lookArea');let hp=100,gameOver=false,firing=false;const zombies=[];const player=new PlayerController(camera,joystick,stick,look,damage=>{if(gameOver)return;hp=Math.max(0,hp-damage);flashDamage();if(hp<=0)die()});
const weapon=new Weapon(THREE,camera,scene,()=>zombies,updateAmmo);function spawn(){for(let i=0;i<9;i++){const a=Math.random()*Math.PI*2,d=14+Math.random()*28;zombies.push(new Zombie(THREE,scene,new THREE.Vector3(Math.sin(a)*d,0,Math.cos(a)*d),player,damage=>{hp=Math.max(0,hp-damage);flashDamage();if(hp<=0)die()}))}}spawn();
function updateAmmo(m,r,reloading){document.querySelector('#mag').textContent=m;document.querySelector('#reserve').textContent=r;document.querySelector('#weaponName').textContent=reloading?'RAVEN-9 / RELOADING':'RAVEN-9'}function flashDamage(){const d=document.querySelector('#damage');d.style.opacity='.35';setTimeout(()=>d.style.opacity='0',100)}function die(){gameOver=true;firing=false;player.setEnabled(false);document.querySelector('#gameOver').style.display='flex'}
function shoot(){if(!gameOver)weapon.fire()}document.querySelector('#fire').addEventListener('pointerdown',e=>{e.preventDefault();firing=true;shoot()});['pointerup','pointercancel','pointerleave'].forEach(t=>document.querySelector('#fire').addEventListener(t,()=>firing=false));document.querySelector('#reload').addEventListener('pointerdown',e=>{e.preventDefault();weapon.reload()});document.querySelector('#jump').addEventListener('pointerdown',e=>{e.preventDefault();player.jump()});document.querySelector('#restart').addEventListener('click',()=>location.reload());addEventListener('blur',()=>firing=false);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
let last=performance.now();function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(!gameOver){player.update(dt);weapon.update(dt);if(firing)shoot();for(const z of zombies)z.update(dt)}renderer.render(scene,camera);requestAnimationFrame(loop)}updateAmmo(12,48,false);requestAnimationFrame(loop);
